esphome:
  name: hot-water-sensor-pipe
  friendly_name: Hot Water Sensor Pipe

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API (This ALSO enables secure OTA and a captive portal)
api:

# This section is no longer needed
# ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

# This section is no longer needed
# captive_portal:

one_wire:
  - platform: gpio
    pin: D1

sensor:
  - platform: dallas_temp
    address: 0xb3000000b256a228
    name: "Water Heater Temperature"
    update_interval: 30s
    